//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KInderGarten
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANAGER
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public int ID_CHILD { get; set; }
    
        public virtual CHILD CHILD { get; set; }
    }
}
