//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KInderGarten
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kindergartenEntities1 : DbContext
    {
        public kindergartenEntities1()
            : base("name=kindergartenEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAREGIVER> CAREGIVER { get; set; }
        public virtual DbSet<CHILD> CHILD { get; set; }
        public virtual DbSet<GROUP> GROUP { get; set; }
        public virtual DbSet<MANAGER> MANAGER { get; set; }
        public virtual DbSet<SECRETARY> SECRETARY { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
